version: '2'

services:
  db:
    image: mysql
    volumes:
      - ./database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  nginx:
    image: nginx:alpine
    restart: always
    ports:
     - '8000:80'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./websites:/websites

  fpm:
    image: wordpress:php7.1-fpm-alpine
    restart: always
    volumes:
      - ./conf/fpm.conf:/usr/local/etc/php-fpm.d/zz-fpm.conf
      - ./websites:/websites
